In [1]:
%cd /content

/content

In [2]:
!git clone https://github.com/hackrudra1234/transformer-translation.git

Cloning into 'transformer-translation'...
remote: Enumerating objects: 149, done.
remote: Counting objects: 100% (149/149), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 149 (delta 68), reused 113 (delta 32), pack-reused 0 (from 0)
Receiving objects: 100% (149/149), 248.51 KiB | 1.39 MiB/s, done.
Resolving deltas: 100% (68/68), done.

In [4]:
%cd transformer-translation

/content/transformer-translation

In [16]:
!git pull

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 281 bytes | 281.00 KiB/s, done.
From https://github.com/hackrudra1234/transformer-translation
   16bed36..495145d  main       -> origin/main
Updating 16bed36..495145d
Fast-forward
 config.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

In [5]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [7]:
%pip install -q datasets sacrebleu tqdm pandas matplotlib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 2.1 MB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 7.3 MB/s eta 0:00:00

In [8]:
!git log -1 --oneline

88f8bb3 (HEAD -> main, origin/main, origin/HEAD) Batch Size

In [ ]:
!python main_train.py

======================================================================
DEVICE INFORMATION
======================================================================
Device: cuda
GPU: NVIDIA L4
GPU Memory: 22.03 GB

======================================================================
EXPERIMENT
======================================================================
Experiment name: d128_h8_enc4_dec4_ff512_bs32_lr0.00025initdefaultschedconstant
Checkpoint path: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.00025initdefaultschedconstant.pt
Experiment directory: /content/drive/MyDrive/transformer-translation/experiments
Plot directory: /content/drive/MyDrive/transformer-translation/plots

======================================================================
LOADING DATASET
======================================================================
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Total examples: 51467
Training examples: 46320
Validation examples: 5147

======================================================================
BUILDING VOCABULARY
======================================================================
German vocab: 26953
English vocab: 17627
Training batches: 1448
Validation batches: 161

======================================================================
CREATING TRANSFORMER
======================================================================
Total parameters: 9,825,371
Trainable parameters: 9,825,371

In [15]:
import pandas as pd

results_path = (
    "/content/drive/MyDrive/"
    "transformer-translation/experiments/"
    "results_v3.csv"
)

results = pd.read_csv(results_path)

results

,experiment,d_model,num_heads,d_ff,encoder_layers,decoder_layers,dropout,learning_rate,batch_size,initialization,lr_schedule,warmup_steps,label_smoothing,best_epoch,best_val_loss,best_perplexity,greedy_bleu,beam_bleu,total_time_min,checkpoint_path
0,d128_h8_enc4_dec4_ff512_bs32_lr0.001initdefaul...,128,8,512,4,4,0.10,0.0010,32,default,constant,0,0.1,10,4.677673,107.519550,3.065280,2.753836,16.140430,/content/drive/MyDrive/transformer-translation...
1,d128_h8_enc4_dec4_ff512_bs32_lr0.001initdefaul...,128,8,512,4,4,0.20,0.0010,32,default,constant,0,0.0,10,3.969281,52.946429,2.252962,2.205115,15.627775,/content/drive/MyDrive/transformer-translation...
2,d128_h8_enc4_dec4_ff512_bs32_lr0.001initdefaul...,128,8,512,4,4,0.05,0.0010,32,default,constant,0,0.0,7,3.864388,47.674069,2.345692,2.789912,15.556011,/content/drive/MyDrive/transformer-translation...
3,d128_h8_enc4_dec4_ff512_bs64_lr0.001initdefaul...,128,8,512,4,4,0.10,0.0010,64,default,constant,0,0.0,10,3.895965,49.203536,2.495970,3.182264,10.113216,/content/drive/MyDrive/transformer-translation...
4,d128_h8_enc4_dec4_ff512_bs32_lr0.0005initdefau...,128,8,512,4,4,0.10,0.0005,32,default,constant,0,0.0,10,3.869201,47.904079,2.866439,2.985070,9.760948,/content/drive/MyDrive/transformer-translation...

In [17]:
import pandas as pd

history = pd.read_csv( "/content/drive/MyDrive/transformer-translation/experiments/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavier_history.csv"
)

history

   epoch  train_loss  val_loss   perplexity  epoch_time_min
0      1    6.237672  7.057453  1161.482848        1.553419
1      2    6.130836  7.488578  1787.508547        1.553361
2      3    6.104022  7.343563  1546.211663        1.556469
3      4    6.092220  7.583595  1965.682979        1.552653
4      5    6.078740  7.802510  2446.735223        1.556901
5      6    6.070748  8.199196  3638.022978        1.558929
6      7    6.067168  8.348537  4223.997005        1.563685
7      8    6.043494  8.592169  5389.288673        1.561409
8      9    6.011452  8.161287  3502.692072        1.546956
9     10    6.005712  8.182855  3579.059663        1.561419