In [1]:
%cd /content

/content

In [2]:
!git clone https://github.com/hackrudra1234/transformer-translation.git

Cloning into 'transformer-translation'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 94 (delta 33), reused 78 (delta 17), pack-reused 0 (from 0)
Receiving objects: 100% (94/94), 235.12 KiB | 1.23 MiB/s, done.
Resolving deltas: 100% (33/33), done.

In [3]:
%cd transformer-translation

/content/transformer-translation

In [21]:
!git pull

remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 8 (delta 5), reused 8 (delta 5), pack-reused 0 (from 0)
Unpacking objects: 100% (8/8), 1.63 KiB | 557.00 KiB/s, done.
From https://github.com/hackrudra1234/transformer-translation
   2a42b02..99f4a9a  main       -> origin/main
Updating 2a42b02..99f4a9a
Fast-forward
 config.py                   |  1 +
 experiments/logger.py       |  6 +++
 main_train.py               | 10 ++++-
 notebook/train_collab.ipynb | 98 +++++++++++++++++++++++++--------------------
 4 files changed, 70 insertions(+), 45 deletions(-)

In [5]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [6]:
%pip install -q datasets sacrebleu tqdm pandas matplotlib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 14.3 MB/s eta 0:00:00

In [7]:
!git log -1 --oneline

3e25ee3 (HEAD -> main, origin/main, origin/HEAD) Adding bleu config

In [19]:
!python main_train.py

======================================================================
DEVICE INFORMATION
======================================================================
Device: cuda
GPU: Tesla T4
GPU Memory: 14.56 GB

======================================================================
EXPERIMENT
======================================================================
Experiment name: d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer
Checkpoint path: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Experiment directory: /content/drive/MyDrive/transformer-translation/experiments
Plot directory: /content/drive/MyDrive/transformer-translation/plots

======================================================================
LOADING DATASET
======================================================================
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Total examples: 51467
Training examples: 46320
Validation examples: 5147

======================================================================
BUILDING VOCABULARY
======================================================================
German vocab: 26953
English vocab: 17627
Training batches: 1448
Validation batches: 161

======================================================================
CREATING TRANSFORMER
======================================================================
Total parameters: 9,825,371
Trainable parameters: 9,825,371

======================================================================
MODEL CONFIGURATION
======================================================================
D_MODEL: 128
NUM_HEADS: 8
D_FF: 512
ENCODER LAYERS: 4
DECODER LAYERS: 4
DROPOUT: 0.1
BATCH SIZE: 32
INITIALIZATION: xavier
LR SCHEDULE: transformer
WARMUP STEPS: 4000
LEARNING RATE: 0.001
EPOCHS: 10
BLEU MAX EXAMPLES: 100
BEAM SIZE: 4
LENGTH PENALTY: 0.6

======================================================================
STARTING TRAINING
======================================================================
Epoch 01/10 | Train Loss: 6.3664 | Val Loss: 4.9713 | PPL: 144.22 | LR: 0.000506 | Time: 1.48 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Epoch 02/10 | Train Loss: 4.8444 | Val Loss: 4.5827 | PPL: 97.78 | LR: 0.001012 | Time: 1.53 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Epoch 03/10 | Train Loss: 4.5551 | Val Loss: 4.3862 | PPL: 80.33 | LR: 0.001341 | Time: 1.56 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Epoch 04/10 | Train Loss: 4.3333 | Val Loss: 4.2533 | PPL: 70.34 | LR: 0.001161 | Time: 1.56 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Epoch 05/10 | Train Loss: 4.1583 | Val Loss: 4.1756 | PPL: 65.08 | LR: 0.001039 | Time: 1.56 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Epoch 06/10 | Train Loss: 4.0318 | Val Loss: 4.1308 | PPL: 62.23 | LR: 0.000948 | Time: 1.56 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Epoch 07/10 | Train Loss: 3.9302 | Val Loss: 4.1042 | PPL: 60.60 | LR: 0.000878 | Time: 1.57 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Epoch 08/10 | Train Loss: 3.8451 | Val Loss: 4.0954 | PPL: 60.06 | LR: 0.000821 | Time: 1.57 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt
Epoch 09/10 | Train Loss: 3.7741 | Val Loss: 4.1061 | PPL: 60.71 | LR: 0.000774 | Time: 1.57 min
Epoch 10/10 | Train Loss: 3.7142 | Val Loss: 4.0949 | PPL: 60.03 | LR: 0.000735 | Time: 1.55 min
Best model saved: /content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt

======================================================================
LOADING BEST MODEL
======================================================================
Loaded best model from epoch: 10

======================================================================
GREEDY BLEU
======================================================================
Greedy BLEU: 0.92
Greedy BLEU time: 0.31 min

======================================================================
BEAM BLEU
======================================================================
Beam BLEU: 1.61
Beam BLEU time: 1.14 min

======================================================================
GENERATING PLOTS
======================================================================

======================================================================
EXPERIMENT COMPLETE
======================================================================
Experiment: d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer
Best epoch: 10
Best validation loss: 4.0949
Best perplexity: 60.03
Greedy BLEU: 0.92
Beam BLEU: 1.61
Training time: 15.58 minutes
Greedy BLEU time: 0.31 minutes
Beam BLEU time: 1.14 minutes
Peak GPU memory: 8.03 GB

Checkpoint:
/content/drive/MyDrive/transformer-translation/checkpoints/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer.pt

History:
/content/drive/MyDrive/transformer-translation/experiments/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer_history.csv

Results:
/content/drive/MyDrive/transformer-translation/experiments/results_v2.csv

Loss plot:
/content/drive/MyDrive/transformer-translation/plots/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer_loss.png

Perplexity plot:
/content/drive/MyDrive/transformer-translation/plots/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer_perplexity.png

Epoch-time plot:
/content/drive/MyDrive/transformer-translation/plots/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavierschedtransformer_time.png

In [20]:
import pandas as pd

results_path = (
    "/content/drive/MyDrive/"
    "transformer-translation/experiments/"
    "results_v2.csv"
)

results = pd.read_csv(results_path)

results

,experiment,d_model,num_heads,d_ff,encoder_layers,decoder_layers,dropout,learning_rate,batch_size,initialization,best_epoch,best_val_loss,best_perplexity,greedy_bleu,beam_bleu,total_time_min,checkpoint_path
0,d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavier,128,8,512,4,4,0.1,0.001,32,xavier,1,7.057453,1161.482848,0.021501,0.021501,15.573684,/content/drive/MyDrive/transformer-translation...
1,d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavier...,128,8,512,4,4,0.1,0.001,32,xavier,10,4.094881,60.032218,0.915015,1.614576,15.578020,/content/drive/MyDrive/transformer-translation...

In [17]:
import pandas as pd

history = pd.read_csv( "/content/drive/MyDrive/transformer-translation/experiments/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavier_history.csv"
)

history

   epoch  train_loss  val_loss   perplexity  epoch_time_min
0      1    6.237672  7.057453  1161.482848        1.553419
1      2    6.130836  7.488578  1787.508547        1.553361
2      3    6.104022  7.343563  1546.211663        1.556469
3      4    6.092220  7.583595  1965.682979        1.552653
4      5    6.078740  7.802510  2446.735223        1.556901
5      6    6.070748  8.199196  3638.022978        1.558929
6      7    6.067168  8.348537  4223.997005        1.563685
7      8    6.043494  8.592169  5389.288673        1.561409
8      9    6.011452  8.161287  3502.692072        1.546956
9     10    6.005712  8.182855  3579.059663        1.561419