In [1]:
%cd /content

/content

In [1]:
!git clone https://github.com/hackrudra1234/transformer-translation.git

Cloning into 'transformer-translation'...
remote: Enumerating objects: 234, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 234 (delta 125), reused 169 (delta 60), pack-reused 0 (from 0)
Receiving objects: 100% (234/234), 266.21 KiB | 24.20 MiB/s, done.
Resolving deltas: 100% (125/125), done.

In [3]:
%cd transformer-translation

/content/transformer-translation

In [4]:
!git pull

Already up to date.

In [5]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [6]:
%pip install -q datasets sacrebleu tqdm pandas matplotlib sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 15.7 MB/s eta 0:00:00

In [8]:
!git log -1 --oneline

1b3ef75 (HEAD -> main, origin/main, origin/HEAD) os issue

In [7]:
!python main_train.py

======================================================================
DEVICE INFORMATION
======================================================================
Device: cuda
GPU: NVIDIA A100-SXM4-40GB
GPU Memory: 39.49 GB

======================================================================
EXPERIMENT
======================================================================
Experiment name: bpe8000_d128_h8_enc4_dec4_ff512_bs32_lr0.00075initdefaultschedconstanttieFalseb10.9_b20.98_eps1e-09
Checkpoint path: /content/drive/MyDrive/transformer-translation/checkpoints/bpe8000_d128_h8_enc4_dec4_ff512_bs32_lr0.00075initdefaultschedconstanttieFalseb10.9_b20.98_eps1e-09.pt
Experiment directory: /content/drive/MyDrive/transformer-translation/experiments
Plot directory: /content/drive/MyDrive/transformer-translation/plots

======================================================================
LOADING DATASET
======================================================================
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
README.md: 100% 28.1k/28.1k [00:00<00:00, 57.1MB/s]

de-en/train-00000-of-00001.parquet: downloading bytes:  94% 8.24M/8.80M [00:01<00:00, 5.68MB/s,  405kB/s  ]
de-en/train-00000-of-00001.parquet: downloading bytes: 100% 8.59M/8.59M [00:01<00:00, 4.99MB/s,  824kB/s  ]
de-en/train-00000-of-00001.parquet: reconstructing file: 100% 8.80M/8.80M [00:01<00:00, 5.11MB/s,  847kB/s  ]
Generating train split: 100% 51467/51467 [00:00<00:00, 580610.94 examples/s]
Total examples: 51467
Training examples: 46320
Validation examples: 5147

======================================================================
BUILDING VOCABULARY
======================================================================
BPE tokenizer not found. Training 8000 vocabulary tokenizer...
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788351189.985743    2198 sentencepiece_trainer.cc:105] Starts training with :
trainer_spec {
  input: data/bpe_shared_8k_corpus.txt
  input_format:
  model_prefix: data/bpe_shared_8k
  model_type: BPE
  vocab_size: 8000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file:
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 1
  bos_id: 2
  eos_id: 3
  pad_id: 0
  unk_piece: <unk>
  bos_piece: <bos>
  eos_piece: <eos>
  pad_piece: <pad>
  unk_surface:  ⁇
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
I0000 00:00:1788351189.985929    2198 trainer_interface.cc:364] SentenceIterator is not specified. Using MultiFileSentenceIterator.
I0000 00:00:1788351189.985963    2198 trainer_interface.cc:193] Loading corpus: data/bpe_shared_8k_corpus.txt
I0000 00:00:1788351190.012214    2198 trainer_interface.cc:422] Loaded all 92640 sentences
I0000 00:00:1788351190.012417    2198 trainer_interface.cc:440] Adding meta_piece: <pad>
I0000 00:00:1788351190.012425    2198 trainer_interface.cc:440] Adding meta_piece: <unk>
I0000 00:00:1788351190.012428    2198 trainer_interface.cc:440] Adding meta_piece: <bos>
I0000 00:00:1788351190.012430    2198 trainer_interface.cc:440] Adding meta_piece: <eos>
I0000 00:00:1788351190.012468    2198 trainer_interface.cc:445] Normalizing sentences...
I0000 00:00:1788351190.322045    2198 trainer_interface.cc:555] all chars count=11540975
I0000 00:00:1788351190.322106    2198 trainer_interface.cc:578] Alphabet size=149
I0000 00:00:1788351190.322114    2198 trainer_interface.cc:579] Final character coverage=1
I0000 00:00:1788351190.644186    2198 trainer_interface.cc:609] Done! preprocessed 92640 sentences.
I0000 00:00:1788351190.644233    2198 trainer_interface.cc:615] Tokenizing input sentences with whitespace: 92640
I0000 00:00:1788351190.923596    2198 trainer_interface.cc:626] Done! 170769
I0000 00:00:1788351191.311147    2198 bpe_model_trainer.cc:321] Added: freq=57616 size=20 all=3169 active=3019 piece=▁the
I0000 00:00:1788351191.350312    2198 bpe_model_trainer.cc:321] Added: freq=34647 size=40 all=4574 active=4424 piece=▁l
I0000 00:00:1788351191.378275    2198 bpe_model_trainer.cc:321] Added: freq=23459 size=60 all=5506 active=5356 piece=▁be
I0000 00:00:1788351191.402329    2198 bpe_model_trainer.cc:321] Added: freq=18128 size=80 all=7033 active=6883 piece=▁G
I0000 00:00:1788351191.418910    2198 bpe_model_trainer.cc:321] Added: freq=14941 size=100 all=8215 active=8065 piece=▁E
I0000 00:00:1788351191.434077    2198 bpe_model_trainer.cc:321] Added: freq=12038 size=120 all=9555 active=9405 piece=▁F
I0000 00:00:1788351191.443142    2198 bpe_model_trainer.cc:321] Added: freq=10652 size=140 all=10470 active=10320 piece=▁ge
I0000 00:00:1788351191.452538    2198 bpe_model_trainer.cc:321] Added: freq=9197 size=160 all=11309 active=11159 piece=end
I0000 00:00:1788351191.463791    2198 bpe_model_trainer.cc:321] Added: freq=7543 size=180 all=12374 active=12224 piece=de
I0000 00:00:1788351191.472964    2198 bpe_model_trainer.cc:321] Added: freq=6479 size=200 all=13603 active=13453 piece=chen
I0000 00:00:1788351191.482294    2198 bpe_model_trainer.cc:321] Added: freq=5688 size=220 all=14977 active=14827 piece=ft
I0000 00:00:1788351191.492027    2198 bpe_model_trainer.cc:321] Added: freq=5019 size=240 all=16189 active=16039 piece=▁sp
I0000 00:00:1788351191.500551    2198 bpe_model_trainer.cc:321] Added: freq=4542 size=260 all=17623 active=17473 piece=▁An
I0000 00:00:1788351191.507379    2198 bpe_model_trainer.cc:321] Added: freq=4136 size=280 all=18764 active=18614 piece=▁ihm
I0000 00:00:1788351191.514251    2198 bpe_model_trainer.cc:321] Added: freq=3856 size=300 all=19881 active=19731 piece=ang
I0000 00:00:1788351191.520272    2198 bpe_model_trainer.cc:321] Added: freq=3521 size=320 all=21081 active=20931 piece=ther
I0000 00:00:1788351191.524905    2198 bpe_model_trainer.cc:321] Added: freq=3211 size=340 all=21818 active=21668 piece=ru
I0000 00:00:1788351191.529839    2198 bpe_model_trainer.cc:321] Added: freq=3009 size=360 all=22792 active=22642 piece=aus
I0000 00:00:1788351191.534901    2198 bpe_model_trainer.cc:321] Added: freq=2817 size=380 all=23895 active=23745 piece=▁ganz
I0000 00:00:1788351191.538898    2198 bpe_model_trainer.cc:321] Added: freq=2619 size=400 all=24641 active=24491 piece=ound
I0000 00:00:1788351191.542973    2198 bpe_model_trainer.cc:321] Added: freq=2508 size=420 all=25583 active=25433 piece=▁go
I0000 00:00:1788351191.547740    2198 bpe_model_trainer.cc:321] Added: freq=2343 size=440 all=26216 active=26066 piece=▁are
I0000 00:00:1788351191.552406    2198 bpe_model_trainer.cc:321] Added: freq=2178 size=460 all=27080 active=26930 piece=och
I0000 00:00:1788351191.556141    2198 bpe_model_trainer.cc:321] Added: freq=2076 size=480 all=28062 active=27912 piece=ine
I0000 00:00:1788351191.560376    2198 bpe_model_trainer.cc:321] Added: freq=1977 size=500 all=28888 active=28738 piece=▁com
I0000 00:00:1788351191.563962    2198 bpe_model_trainer.cc:321] Added: freq=1884 size=520 all=29933 active=29783 piece=▁sel
I0000 00:00:1788351191.566976    2198 bpe_model_trainer.cc:321] Added: freq=1804 size=540 all=30788 active=30638 piece=▁She
I0000 00:00:1788351191.569487    2198 bpe_model_trainer.cc:321] Added: freq=1732 size=560 all=31407 active=31257 piece=▁seiner
I0000 00:00:1788351191.572949    2198 bpe_model_trainer.cc:321] Added: freq=1656 size=580 all=32401 active=32251 piece=▁sehr
I0000 00:00:1788351191.576586    2198 bpe_model_trainer.cc:321] Added: freq=1579 size=600 all=33238 active=33088 piece=was
I0000 00:00:1788351191.578849    2198 bpe_model_trainer.cc:321] Added: freq=1530 size=620 all=33957 active=33807 piece=▁gr
I0000 00:00:1788351191.581414    2198 bpe_model_trainer.cc:321] Added: freq=1487 size=640 all=34757 active=34607 piece=▁Alex
I0000 00:00:1788351191.584178    2198 bpe_model_trainer.cc:321] Added: freq=1433 size=660 all=35551 active=35401 piece=▁Frau
I0000 00:00:1788351191.586636    2198 bpe_model_trainer.cc:321] Added: freq=1384 size=680 all=35907 active=35757 piece=are
I0000 00:00:1788351191.588558    2198 bpe_model_trainer.cc:321] Added: freq=1356 size=700 all=36465 active=36315 piece=▁still
I0000 00:00:1788351191.590421    2198 bpe_model_trainer.cc:321] Added: freq=1314 size=720 all=37006 active=36856 piece=gt
I0000 00:00:1788351191.592688    2198 bpe_model_trainer.cc:321] Added: freq=1276 size=740 all=37622 active=37472 piece=▁soll
I0000 00:00:1788351191.594669    2198 bpe_model_trainer.cc:321] Added: freq=1229 size=760 all=38076 active=37926 piece=other
I0000 00:00:1788351191.597012    2198 bpe_model_trainer.cc:321] Added: freq=1170 size=780 all=38792 active=38642 piece=ater
I0000 00:00:1788351191.598867    2198 bpe_model_trainer.cc:321] Added: freq=1131 size=800 all=39383 active=39233 piece=▁wen
I0000 00:00:1788351191.601127    2198 bpe_model_trainer.cc:321] Added: freq=1094 size=820 all=40144 active=39994 piece=▁door
I0000 00:00:1788351191.602839    2198 bpe_model_trainer.cc:321] Added: freq=1064 size=840 all=40570 active=40420 piece=▁must
I0000 00:00:1788351191.604653    2198 bpe_model_trainer.cc:321] Added: freq=1028 size=860 all=41119 active=40969 piece=fl
I0000 00:00:1788351191.606363    2198 bpe_model_trainer.cc:321] Added: freq=1000 size=880 all=41592 active=41442 piece=▁somet
I0000 00:00:1788351191.608082    2198 bpe_model_trainer.cc:321] Added: freq=970 size=900 all=42111 active=41961 piece=▁pass
I0000 00:00:1788351191.609958    2198 bpe_model_trainer.cc:321] Added: freq=943 size=920 all=42728 active=42578 piece=▁Ged
I0000 00:00:1788351191.611602    2198 bpe_model_trainer.cc:321] Added: freq=921 size=940 all=43269 active=43119 piece=▁viel
I0000 00:00:1788351191.613429    2198 bpe_model_trainer.cc:321] Added: freq=896 size=960 all=43775 active=43625 piece=▁wa
I0000 00:00:1788351191.615287    2198 bpe_model_trainer.cc:321] Added: freq=868 size=980 all=44417 active=44267 piece=pl
I0000 00:00:1788351191.617309    2198 bpe_model_trainer.cc:321] Added: freq=850 size=1000 all=45306 active=45156 piece=▁bel
I0000 00:00:1788351191.618679    2198 bpe_model_trainer.cc:321] Added: freq=828 size=1020 all=45630 active=45480 piece=reg
I0000 00:00:1788351191.620233    2198 bpe_model_trainer.cc:321] Added: freq=811 size=1040 all=46128 active=45978 piece=sicht
I0000 00:00:1788351191.621665    2198 bpe_model_trainer.cc:321] Added: freq=790 size=1060 all=46479 active=46329 piece=ruck
I0000 00:00:1788351191.623008    2198 bpe_model_trainer.cc:321] Added: freq=774 size=1080 all=46966 active=46816 piece=▁glau
I0000 00:00:1788351191.624452    2198 bpe_model_trainer.cc:321] Added: freq=754 size=1100 all=47431 active=47281 piece=▁gem
I0000 00:00:1788351191.625867    2198 bpe_model_trainer.cc:321] Added: freq=739 size=1120 all=47979 active=47829 piece=ase
I0000 00:00:1788351191.627378    2198 bpe_model_trainer.cc:321] Added: freq=724 size=1140 all=48410 active=48260 piece=▁rec
I0000 00:00:1788351191.629234    2198 bpe_model_trainer.cc:321] Added: freq=708 size=1160 all=49091 active=48941 piece=▁make
I0000 00:00:1788351191.630506    2198 bpe_model_trainer.cc:321] Added: freq=693 size=1180 all=49402 active=49252 piece=▁dachte
I0000 00:00:1788351191.631773    2198 bpe_model_trainer.cc:321] Added: freq=680 size=1200 all=49787 active=49637 piece=essed
I0000 00:00:1788351191.633041    2198 bpe_model_trainer.cc:321] Added: freq=670 size=1220 all=50243 active=50093 piece=orgen
I0000 00:00:1788351191.635112    2198 bpe_model_trainer.cc:321] Added: freq=648 size=1240 all=50854 active=50704 piece=aster
I0000 00:00:1788351191.636975    2198 bpe_model_trainer.cc:321] Added: freq=631 size=1260 all=51418 active=51268 piece=▁work
I0000 00:00:1788351191.638194    2198 bpe_model_trainer.cc:321] Added: freq=621 size=1280 all=51779 active=51629 piece=ingo
I0000 00:00:1788351191.639793    2198 bpe_model_trainer.cc:321] Added: freq=608 size=1300 all=52268 active=52118 piece=under
I0000 00:00:1788351191.641226    2198 bpe_model_trainer.cc:321] Added: freq=596 size=1320 all=52742 active=52592 piece=ften
I0000 00:00:1788351191.642363    2198 bpe_model_trainer.cc:321] Added: freq=588 size=1340 all=53120 active=52970 piece=▁ze
I0000 00:00:1788351191.643660    2198 bpe_model_trainer.cc:321] Added: freq=579 size=1360 all=53472 active=53322 piece=atz
I0000 00:00:1788351191.645142    2198 bpe_model_trainer.cc:321] Added: freq=566 size=1380 all=54001 active=53851 piece=▁fühlte
I0000 00:00:1788351191.646619    2198 bpe_model_trainer.cc:321] Added: freq=557 size=1400 all=54522 active=54372 piece=▁hast
I0000 00:00:1788351191.647841    2198 bpe_model_trainer.cc:321] Added: freq=550 size=1420 all=55047 active=54897 piece=▁light
I0000 00:00:1788351191.649099    2198 bpe_model_trainer.cc:321] Added: freq=536 size=1440 all=55385 active=55235 piece=▁far
I0000 00:00:1788351191.650170    2198 bpe_model_trainer.cc:321] Added: freq=529 size=1460 all=55799 active=55649 piece=▁read
I0000 00:00:1788351191.651124    2198 bpe_model_trainer.cc:321] Added: freq=518 size=1480 all=56065 active=55915 piece=ER
I0000 00:00:1788351191.652141    2198 bpe_model_trainer.cc:321] Added: freq=511 size=1500 all=56371 active=56221 piece=▁When
I0000 00:00:1788351191.653302    2198 bpe_model_trainer.cc:321] Added: freq=502 size=1520 all=56697 active=56547 piece=▁ber
I0000 00:00:1788351191.654253    2198 bpe_model_trainer.cc:321] Added: freq=497 size=1540 all=57005 active=56855 piece=▁heraus
I0000 00:00:1788351191.656225    2198 bpe_model_trainer.cc:321] Added: freq=491 size=1560 all=57226 active=57076 piece=ertain
I0000 00:00:1788351191.657164    2198 bpe_model_trainer.cc:321] Added: freq=485 size=1580 all=57531 active=57381 piece=ucht
I0000 00:00:1788351191.658333    2198 bpe_model_trainer.cc:321] Added: freq=477 size=1600 all=57904 active=57754 piece=▁tro
I0000 00:00:1788351191.659244    2198 bpe_model_trainer.cc:321] Added: freq=470 size=1620 all=58220 active=58070 piece=bed
I0000 00:00:1788351191.660113    2198 bpe_model_trainer.cc:321] Added: freq=464 size=1640 all=58557 active=58407 piece=▁cur
I0000 00:00:1788351191.660988    2198 bpe_model_trainer.cc:321] Added: freq=457 size=1660 all=58944 active=58794 piece=Und
I0000 00:00:1788351191.662131    2198 bpe_model_trainer.cc:321] Added: freq=452 size=1680 all=59400 active=59250 piece=▁trat
I0000 00:00:1788351191.663352    2198 bpe_model_trainer.cc:321] Added: freq=443 size=1700 all=59807 active=59657 piece=gehen
I0000 00:00:1788351191.664514    2198 bpe_model_trainer.cc:321] Added: freq=436 size=1720 all=60256 active=60106 piece=▁Über
I0000 00:00:1788351191.665844    2198 bpe_model_trainer.cc:321] Added: freq=429 size=1740 all=60823 active=60673 piece=▁Quasimodo
I0000 00:00:1788351191.667132    2198 bpe_model_trainer.cc:321] Added: freq=423 size=1760 all=61443 active=61293 piece=ruder
I0000 00:00:1788351191.668059    2198 bpe_model_trainer.cc:321] Added: freq=415 size=1780 all=61686 active=61536 piece=hör
I0000 00:00:1788351191.669255    2198 bpe_model_trainer.cc:321] Added: freq=409 size=1800 all=62123 active=61973 piece=▁setzte
I0000 00:00:1788351191.670245    2198 bpe_model_trainer.cc:321] Added: freq=401 size=1820 all=62386 active=62236 piece=ürlich
I0000 00:00:1788351191.670992    2198 bpe_model_trainer.cc:321] Added: freq=396 size=1840 all=62636 active=62486 piece=▁help
I0000 00:00:1788351191.671854    2198 bpe_model_trainer.cc:321] Added: freq=390 size=1860 all=62910 active=62760 piece=▁Mar
I0000 00:00:1788351191.672560    2198 bpe_model_trainer.cc:321] Added: freq=385 size=1880 all=63140 active=62990 piece=▁hinzu
I0000 00:00:1788351191.673426    2198 bpe_model_trainer.cc:321] Added: freq=380 size=1900 all=63478 active=63328 piece=▁sub
I0000 00:00:1788351191.674474    2198 bpe_model_trainer.cc:321] Added: freq=374 size=1920 all=63757 active=63607 piece=▁Seite
I0000 00:00:1788351191.675271    2198 bpe_model_trainer.cc:321] Added: freq=370 size=1940 all=64093 active=63943 piece=▁blieb
I0000 00:00:1788351191.676178    2198 bpe_model_trainer.cc:321] Added: freq=365 size=1960 all=64443 active=64293 piece=PTER
I0000 00:00:1788351191.676923    2198 bpe_model_trainer.cc:321] Added: freq=361 size=1980 all=64747 active=64597 piece=▁poor
I0000 00:00:1788351191.677539    2198 bpe_model_trainer.cc:321] Added: freq=357 size=2000 all=64885 active=64735 piece=▁Arbeit
I0000 00:00:1788351191.678400    2198 bpe_model_trainer.cc:321] Added: freq=353 size=2020 all=65262 active=65112 piece=▁erh
I0000 00:00:1788351191.679171    2198 bpe_model_trainer.cc:321] Added: freq=349 size=2040 all=65568 active=65418 piece=ährend
I0000 00:00:1788351191.680925    2198 bpe_model_trainer.cc:321] Added: freq=344 size=2060 all=65886 active=65736 piece=cept
I0000 00:00:1788351191.681783    2198 bpe_model_trainer.cc:321] Added: freq=339 size=2080 all=66164 active=66014 piece=▁sim
I0000 00:00:1788351191.682435    2198 bpe_model_trainer.cc:321] Added: freq=335 size=2100 all=66342 active=66192 piece=▁besser
I0000 00:00:1788351191.683434    2198 bpe_model_trainer.cc:321] Added: freq=330 size=2120 all=66652 active=66502 piece=zte
I0000 00:00:1788351191.684051    2198 bpe_model_trainer.cc:321] Added: freq=327 size=2140 all=66829 active=66679 piece=elnd
I0000 00:00:1788351191.684853    2198 bpe_model_trainer.cc:321] Added: freq=323 size=2160 all=67143 active=66993 piece=onstant
I0000 00:00:1788351191.685877    2198 bpe_model_trainer.cc:321] Added: freq=318 size=2180 all=67547 active=67397 piece=▁front
I0000 00:00:1788351191.686728    2198 bpe_model_trainer.cc:321] Added: freq=313 size=2200 all=67868 active=67718 piece=utes
I0000 00:00:1788351191.687557    2198 bpe_model_trainer.cc:321] Added: freq=310 size=2220 all=68215 active=68065 piece=reng
I0000 00:00:1788351191.688344    2198 bpe_model_trainer.cc:321] Added: freq=307 size=2240 all=68470 active=68320 piece=▁red
I0000 00:00:1788351191.689108    2198 bpe_model_trainer.cc:321] Added: freq=304 size=2260 all=68762 active=68612 piece=falls
I0000 00:00:1788351191.689916    2198 bpe_model_trainer.cc:321] Added: freq=301 size=2280 all=69089 active=68939 piece=▁together
I0000 00:00:1788351191.690516    2198 bpe_model_trainer.cc:321] Added: freq=297 size=2300 all=69247 active=69097 piece=spr
I0000 00:00:1788351191.691534    2198 bpe_model_trainer.cc:321] Added: freq=294 size=2320 all=69670 active=69520 piece=▁sen
I0000 00:00:1788351191.692139    2198 bpe_model_trainer.cc:321] Added: freq=291 size=2340 all=69883 active=69733 piece=▁women
I0000 00:00:1788351191.693037    2198 bpe_model_trainer.cc:321] Added: freq=287 size=2360 all=70226 active=70076 piece=kun
I0000 00:00:1788351191.693768    2198 bpe_model_trainer.cc:321] Added: freq=284 size=2380 all=70530 active=70380 piece=▁Seit
I0000 00:00:1788351191.694479    2198 bpe_model_trainer.cc:321] Added: freq=281 size=2400 all=70801 active=70651 piece=rauen
I0000 00:00:1788351191.695006    2198 bpe_model_trainer.cc:321] Added: freq=278 size=2420 all=70994 active=70844 piece=irc
I0000 00:00:1788351191.695817    2198 bpe_model_trainer.cc:321] Added: freq=275 size=2440 all=71288 active=71138 piece=nehmen
I0000 00:00:1788351191.696537    2198 bpe_model_trainer.cc:321] Added: freq=273 size=2460 all=71601 active=71451 piece=▁besonders
I0000 00:00:1788351191.697043    2198 bpe_model_trainer.cc:321] Added: freq=270 size=2480 all=71797 active=71647 piece=▁ru

In [8]:
import pandas as pd

results_path = (
    "/content/drive/MyDrive/"
    "transformer-translation/experiments/"
    "results_v6.csv"
)

results = pd.read_csv(results_path)

results

,experiment,d_model,num_heads,d_ff,encoder_layers,decoder_layers,dropout,learning_rate,batch_size,initialization,...,adam_beta1,adam_beta2,adam_eps,best_epoch,best_val_loss,best_perplexity,greedy_bleu,beam_bleu,total_time_min,checkpoint_path
0,bpe16k_d128_h8_enc4_dec4_ff512_bs32_lr0.00075i...,128,8,512,4,4,0.1,0.00075,32,default,...,0.9,0.98,1.000000e-09,20,3.959847,52.449279,3.704305,4.306684,21.843896,/content/drive/MyDrive/transformer-translation...
1,bpe8000_d128_h8_enc4_dec4_ff512_bs32_lr0.00075...,128,8,512,4,4,0.1,0.00075,32,default,...,0.9,0.98,1.000000e-09,20,3.672899,39.365863,3.929490,4.703868,16.572420,/content/drive/MyDrive/transformer-translation...

In [17]:
import pandas as pd

history = pd.read_csv( "/content/drive/MyDrive/transformer-translation/experiments/d128_h8_enc4_dec4_ff512_bs32_lr0.001initxavier_history.csv"
)

history

   epoch  train_loss  val_loss   perplexity  epoch_time_min
0      1    6.237672  7.057453  1161.482848        1.553419
1      2    6.130836  7.488578  1787.508547        1.553361
2      3    6.104022  7.343563  1546.211663        1.556469
3      4    6.092220  7.583595  1965.682979        1.552653
4      5    6.078740  7.802510  2446.735223        1.556901
5      6    6.070748  8.199196  3638.022978        1.558929
6      7    6.067168  8.348537  4223.997005        1.563685
7      8    6.043494  8.592169  5389.288673        1.561409
8      9    6.011452  8.161287  3502.692072        1.546956
9     10    6.005712  8.182855  3579.059663        1.561419